Repository N3ROO/Bettercolors, pull requests merged in 2019-12, with the labels that each got.

#33 Added feature #30 for MC1.14.4
  CHANGELOG.MD
  src/main/java/com/bettercolors/main/Bettercolors.java
  src/main/java/com/bettercolors/view/Window.java
Labels: MC 1.14.4, enhancement

#34 Fixed issue #29 for MC1.14.4
  CHANGELOG.MD
  src/main/java/com/bettercolors/modules/AimAssistance.java
Labels: MC 1.14.4, bug

#35 Added feature #15 for MC1.14.4
  src/main/java/com/bettercolors/main/Bettercolors.java
  src/main/java/com/bettercolors/utils/VKtoGLFW.java
  src/main/java/com/bettercolors/view/Window.java
Labels: MC 1.14.4, enhancement

#36 Design #23 for MC1.14.4
  src/main/java/com/bettercolors/io/Filer.java
  src/main/java/com/bettercolors/io/SettingsUtils.java
Labels: MC 1.14.4, design
